name: incepto_rover
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  adobe_xd: ^2.0.0+1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  holding_gesture: ^1.1.0
  http: ^0.13.4
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
